### ISSUE TITLE
[v2] Scan results coming in graphs but not being reflected in corresponding scan tabs

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1175] opened 2023-05-30 11:11 UTC
**Describe the bug**
When a vuln/secrets/malware/compliance scan is in progress, the results are shown after a while in the graphs but no results in the corresponding scan tabs.

**Screenshots**
Graph in scan section
![Screenshot 2023-05-29 at 4 33 03 PM](https://github.com/deepfence/ThreatMapper/assets/4747605/960170a7-f4f2-40c2-a95f-394e39e0703a)
Graph on topology
![Screenshot 2023-05-29 at 4 32 35 PM](https://github.com/deepfence/ThreatMapper/assets/4747605/6de39a9a-2527-45dc-82e9-0643d45323b1)

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by gnmahanth** [comment] 2023-05-30 11:14
duplicate of  https://github.com/deepfence/enterprise-roadmap/issues/1764

**Comment by shyam-dev** [comment] 2023-06-01 21:18
Closing this as it is being tracked elsewhere

**Closed by shyam-dev** 2023-06-01 21:18 UTC
Labels: bug, needs-triage
